<a href="https://colab.research.google.com/github/2303a51027/ADM_Lab/blob/main/Lab_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as nmp
import matplotlib.pyplot as plt
import pandas as pd
import kagglehub


DS = pd.read_csv("wine.csv")

X = DS.iloc[:, 0:13].values
Y = DS.iloc[:, 13].values

print(DS.head())


   Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735  


In [ ]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, Y_train, Y_test = tts(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.decomposition import PCA
Pca = PCA(n_components = 1)
X_train = Pca.fit_transform(X_train)
X_test = Pca.transform(X_test)
explained_variance = Pca.explained_variance_ratio_

In [17]:
from sklearn.linear_model import LogisticRegression as LR
classifier_1 = LR(random_state = 0)
classifier_1.fit(X_train, Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [19]:
Y_pred = classifier_1.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix as CM
c_m = CM(Y_test, Y_pred)
print(c_m)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
from matplotlib.colors import ListedColormap as Lcm
X_set, Y_set = X_train, Y_train
X_1, X_2 = nmp.meshgrid(nmp.arange(start = X_set[:, 0].min() - 1,
                                   stop = X_set[:, 0].max() + 1, step = 0.01),
                         nmp.arange(start = X_set[:, 1].min() - 1,
                                   stop = X_set[:, 1].max() + 1, step = 0.01))

plt.contourf(X_1, X_2, classifier_1.predict(nmp.array([X_1.ravel(), X_2.ravel()]).T).reshape(X_1.shape),
                           alpha = 0.75, cmap = Lcm(('red', 'green')))

IndexError: index 1 is out of bounds for axis 1 with size 1

In [ ]:
import matplotlib.pyplot as mpltl

mpltl.xlim(X_1.min(), X_1.max())
mpltl.ylim(X_2.min(), X_2.max())

for s, t in enumerate(nmp.unique(Y_set)):
    mpltl.scatter(X_set[Y_set == t, 0], X_set[Y_set == t, 1], c = LCM(('red', 'green', 'blue'))(s), label = t)